pipeline {
    agent {
        docker {
            image 'maven:3.9.4'
            args '-u 1000:1000 -v /home/jenkins/.m2:/root/.m2'
        }
    }
    environment {
        APP_ENV = 'production'
        VERSION = '1.0.0'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                success {
                    echo 'Tests passed successfully.'
                }
                failure {
                    echo 'Tests failed. Check the reports for details.'
                }
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'mvn -B -Dmaven.repo.local=/root/.m2/repository -DskipTests clean package'
            }
        }
    }
}
