pipeline {
    agent {
        docker {
            image 'maven:3.9.4'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        JAVA_HOME = '/opt/java/openjdk' // Default Java path in Maven Docker images
        PATH = "${JAVA_HOME}/bin:${env.PATH}" // Add Java to PATH
    }
    stages {
        stage('Verify Environment') {
            steps {
                sh 'java -version' // Verify Java is available
                sh 'mvn -v'        // Verify Maven detects Java
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
